#!/bin/bash

# WARNING: this script has a limitation - it will not work if CWEB and/or CH file
#          contain '@i' which reference non-ASCII files (atl.w is ASCII, so it's OK, and it work because cp866 is used here).
#          To use this script on such CWEB and CH files you have to convert the
#          referenced files manually to cp866 (TeX internal encoding) temporarily.
#          WAIT! you may use wmerge like in ccw, but you will have to expand
#          both converted and original file to make the check valid, but then
#          above note will not be true if you use a change-file, unless you call it with
#          change-file in the end of this script again

test -z "$1" && exit 1
if [ `dirname "$1"` != . ] || [ `dirname "$2"` != . ]; then
  echo master file and change file must be in current directory
  exit 1
fi
TMPDIR=$(mktemp -d -p /tmp XXXXXXXXXX)
OUTFILE=`basename "$1" .w`
[ "$3" != "" ] && OUTFILE=`dirname "$3"`/`basename "$3" .w`
TMPFILE=$TMPDIR/`basename "$OUTFILE"`
INFILE=`basename "$1" .w`.w
test -e "$INFILE" || INFILE="$1".web
if ! test -e "$INFILE"; then
  echo Wrong web filename
  exit 1
fi
if [ "$2" != "" ] && [ "$2" != "-" ]; then
  CHFILE=`basename "$2" .ch`.ch
  if ! test -e "$CHFILE"; then
    echo Wrong ch filename
    exit 1
  fi
fi
ABS_INFILE=`readlink -f "$INFILE"`
if grep -q "^$ABS_INFILE lock$" /tmp/em.db; then echo file $INFILE is being edited; exit; fi
if [ "$CHFILE" != "" ]; then
  ABS_CHFILE=`readlink -f "$CHFILE"`
  if grep -q "^$ABS_CHFILE lock$" /tmp/em.db; then echo file $CHFILE is being edited; exit; fi
fi
iconv -t cp866 "$INFILE" > $TMPDIR/"$INFILE" || exit
if [ "$CHFILE" != "" ]; then
  iconv -t cp866 "$CHFILE" > $TMPDIR/"$CHFILE" || exit
fi
cat $TMPDIR/"$INFILE" > "$INFILE"
[ "$CHFILE" != "" ] && cat $TMPDIR/"$CHFILE" > "$CHFILE"
/var/local/bin/ctangle "$@" | iconv -f cp866 > "$TMPFILE".out-orig
iconv -f cp866 "$INFILE" | sponge "$INFILE"
[ "$CHFILE" != "" ] && iconv -f cp866 "$CHFILE" | sponge "$CHFILE"
iconv -f cp866 "$OUTFILE".c > "$TMPFILE".c
/usr/local/bin/ctangle "$@" > "$TMPFILE".out
CWEB_RES=$?
if ! diff "$TMPFILE".c "$OUTFILE".c > /dev/null; then
  diff -au "$TMPFILE".c "$OUTFILE".c | colordiff
  RES=FAIL
fi
if ! diff "$TMPFILE".out-orig "$TMPFILE".out > /dev/null; then
  diff -au "$TMPFILE".out-orig "$TMPFILE".out | colordiff
  RES=FAIL
fi
rm -fr $TMPDIR
