--- tmp/cweb-my/Makefile       2022-11-04 18:58:23.000000000 +0700
+++ Makefile       2022-11-10 14:34:36.962651987 +0700
@@ -1,10 +1,10 @@
 all:
-       make -C bin
-       bin/ctie -c comm-merged.ch common.w common-utf8.ch comm-utf8.ch comm-bhp.ch >/dev/null
+       @make --no-print-directory -C bin
+       ctie -c comm-merged.ch common.w common-utf8.ch comm-utf8.ch comm-bhp.ch >/dev/null
        bin/ctangle common comm-merged
-       bin/ctie -c cweav-merged.ch cweave.w common-utf8.ch cweav-utf8.ch cweav-sort.ch cweave+c.ch cweave+d.ch cweave+g.ch cweave+y.ch cweave+z.ch >/dev/null # TODO: check what is +g via dvidiff
+       ctie -c cweav-merged.ch cweave.w common-utf8.ch cweav-utf8.ch cweav-sort.ch cweave+c.ch cweave+d.ch cweave+g.ch cweave+y.ch cweave+z.ch >/dev/null # TODO: check what is +g via dvidiff
        bin/ctangle cweave cweav-merged
        gcc -w -o cweave cweave.c common.c
-       bin/ctie -c ctang-merged.ch ctangle.w common-utf8.ch ctang-utf8.ch ctang-bhp.ch ctang-pre.ch ctangle+u.ch >/dev/null
+       ctie -c ctang-merged.ch ctangle.w common-utf8.ch ctang-utf8.ch ctang-bhp.ch ctang-pre.ch ctangle+u.ch >/dev/null
        bin/ctangle ctangle ctang-merged
        gcc -w -o ctangle ctangle.c common.c
