#!/bin/bash
cd /home/user/cwebtest/
git checkout .
git reset >/dev/null
git checkout .
git clean -f >/dev/null
git checkout master &>/dev/null
git branch -D runall-/bin/-V runall-/home/user/cweb-git/-V &>/dev/null
./runall.sh -p /bin/ >runall.log 2>/dev/null
git checkout runall-/bin/-V &>/dev/null
git add runall.log
git commit -m 'runall' >/dev/null
git checkout master &>/dev/null
./runall.sh -p /home/user/cweb-git/ >runall.log 2>/dev/null
git checkout runall-/home/user/cweb-git/-V &>/dev/null
git add runall.log
git commit -m 'runall' >/dev/null
git commit -m 'cwebmac' . >/dev/null
git checkout master &>/dev/null
git diff runall-/bin/-V runall-/home/user/cweb-git/-V
