#!/bin/bash
cd /home/user/cwebtest/
git checkout -q .
git reset >/dev/null
git checkout -q .
git clean -f >/dev/null
git checkout master &>/dev/null
git branch -D runall-/usr/local/bin/cweb-dek/-V3.64 runall-/home/user/cweb-git/-V3.64 &>/dev/null
./runall.sh -p /usr/local/bin/cweb-dek/ >runall.log 2>/dev/null
git checkout runall-/usr/local/bin/cweb-dek/-V3.64 &>/dev/null
git add runall.log
git commit -m 'runall' >/dev/null
git checkout master &>/dev/null
./runall.sh -p /home/user/cweb-git/ >runall.log 2>/dev/null
git checkout runall-/home/user/cweb-git/-V3.64 &>/dev/null
git add runall.log
git commit -m 'runall' >/dev/null
git commit -m 'cwebmac' . >/dev/null
git checkout master &>/dev/null
git diff runall-/usr/local/bin/cweb-dek/-V3.64 runall-/home/user/cweb-git/-V3.64
