#!/bin/sh
rm -f $1.toc
/home/user/tex/plain $1 || exit
if [ -e $1.toc ] && grep -q '^\\endinput [0-9]\+$' $1.toc; then
  toc=`sed -n 's/^\\\\endinput \([0-9]\+\)$/\1/p' $1.toc`
  total=`sed -n 's/^Output written on .* (\([0-9]\+\) pages\?, [0-9]\+ bytes\?)\.$/\1/p' $1.log`
  num_pages_in_toc=`echo $total - $toc + 1 | bc`
  printf %s%s '\batchmode \def\xyz{\pageno=\contentspagenumber \advance\pageno'$num_pages_in_toc '} \input '$1 | /home/user/tex/plain >/dev/null
  #cut end and paste to beg
fi
