#!/bin/bash
for i in `awk '{ print $2 }' types.w`; do
  X=$(grep "\b$i\*\?:" headers|cut -d: -f1)
  H=$(grep "\b$i\*\?:" headers|cut -d: -f2|cut -d' ' -f2)
  A=$(grep "\b$i\*\?:" headers|cut -d: -f2|cut -d' ' -f3-)
  #echo "DEBUG $i: type = $X; header = $H; args = $A"
  cat <<EOF >x.c
#ifdef H
#include <$H>
#endif
void main(void)
{
  $X x;
}
EOF
  gcc -o /dev/null x.c $A 2>/dev/null
  RET1=$?
  gcc -DH -o /dev/null x.c $A 2>/dev/null
  RET2=$?
  if [ $RET1 != 0 ] && [ $RET2 = 0 ]; then
    true
  else
    echo $i fail
  fi
done
