#!/bin/bash

# WARNING: this script has a limitation - it will not work if CWEB and/or CH file
#          contain '@i' which reference non-ASCII files (atl.w is ASCII, so it's OK, and it works because it does not influence cweave).
#          To use this script on such CWEB and CH files you have to convert the
#          referenced files manually to cp1251 temporarily. WAIT! you may use wmerge to
#          expand '@i' (use special wmerge, built specifically for this case,
#          which tolerates longer strings (to handle UTF-8) - see something like commit
#          5fe018ddee917ad41bc08403b6ca36b022f7b033)

test -z "$1" && exit 1
if [ `dirname "$1"` != . ] || [ `dirname "$2"` != . ]; then
  echo master file and change file must be in current directory
  exit 1
fi
TMPDIR=$(mktemp -d -p /tmp XXXXXXXXXX)
OUTFILE=`basename "$1" .w`
[ "$3" != "" ] && OUTFILE=`dirname "$3"`/`basename "$3" .w`
TMPFILE=$TMPDIR/`basename "$OUTFILE"`
INFILE=`basename "$1" .w`.w
test -e "$INFILE" || INFILE="$1".web
if ! test -e "$INFILE"; then
  echo Wrong web filename
  exit 1
fi
if [ "$2" != "" ] && [ "$2" != "-" ]; then
  CHFILE=`basename "$2" .ch`.ch
  if ! test -e "$CHFILE"; then
    echo Wrong ch filename
    exit 1
  fi
fi
ABS_INFILE=`readlink -f "$INFILE"`
if grep -q "^$ABS_INFILE lock$" /tmp/em.db; then echo file $INFILE is being edited; exit; fi
if [ "$CHFILE" != "" ]; then
  ABS_CHFILE=`readlink -f "$CHFILE"`
  if grep -q "^$ABS_CHFILE lock$" /tmp/em.db; then echo file $CHFILE is being edited; exit; fi
fi
iconv -t cp1251 "$INFILE" > $TMPDIR/"$INFILE" || exit
if [ "$CHFILE" != "" ]; then
  iconv -t cp1251 "$CHFILE" > $TMPDIR/"$CHFILE" || exit
fi
cat $TMPDIR/"$INFILE" > "$INFILE"
[ "$CHFILE" != "" ] && cat $TMPDIR/"$CHFILE" > "$CHFILE"
sed -i /cwebmac-ru/d "$INFILE"
/var/local/bin/cweave +a "$@" | iconv -f cp1251 > "$TMPFILE".out-orig
iconv -f cp1251 $TMPDIR/"$INFILE" >"$INFILE"
[ "$CHFILE" != "" ] && iconv -f cp1251 "$CHFILE" | sponge "$CHFILE"
iconv -f cp1251 "$OUTFILE".idx > "$TMPFILE".idx
iconv -f cp1251 "$OUTFILE".scn > "$TMPFILE".scn
iconv -f cp1251 "$OUTFILE".tex > "$TMPFILE".tex
/usr/local/bin/cweave +a "$@" > "$TMPFILE".out
CWEB_RES=$?
if ! sed s/cwebmac-ru/cwebmac/ "$OUTFILE".tex | diff "$TMPFILE".tex - >/dev/null; then
  sed s/cwebmac-ru/cwebmac/ "$OUTFILE".tex | diff -au "$TMPFILE".tex - | colordiff
  RES=FAIL
fi
if ! diff "$TMPFILE".idx "$OUTFILE".idx > /dev/null; then
  diff -au "$TMPFILE".idx "$OUTFILE".idx | colordiff
  RES=FAIL
fi
if ! diff "$TMPFILE".scn "$OUTFILE".scn > /dev/null; then
  diff -au "$TMPFILE".scn "$OUTFILE".scn | colordiff
  RES=FAIL
fi
if ! diff "$TMPFILE".out-orig "$TMPFILE".out > /dev/null; then
  diff -au "$TMPFILE".out-orig "$TMPFILE".out | colordiff
  RES=FAIL
fi
rm -fr $TMPDIR
